# Generated by Django 4.2.19 on 2025-02-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("big_models", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aimodellink",
            options={"ordering": ["click_count", "order"]},
        ),
        migrations.AddField(
            model_name="aimodellink",
            name="click_count",
            field=models.IntegerField(default=0),
        ),
    ]
